services:
  pytorch-2.4.2:
    image:  myano000/pytorch:2.4.1
    user: root
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - "/mnt/c/Dev:/workspace"
    container_name: pytorch-2.4.1-container
    command: /bin/bash -c "apt-get update && cd /workspace && jupyter-lab --no-browser --port=8888 --ip=0.0.0.0  --allow-root --NotebookApp.token= && /bin/bash"
    tty: true
